language: bash
services:
- docker
- mongodb
addons:
  ssh_known_hosts: 52.13.20.197
before_script:
- sleep 15
- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- cp .env.example .env
- docker-compose up -d
before_install:
- openssl aes-256-cbc -K $encrypted_901d321fc196_key -iv $encrypted_901d321fc196_iv
  -in deploy.pem.enc -out deploy.pem -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 52.13.20.197\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- cd /var/www/parser-server
- sudo git checkout master
- sudo git pull origin master
- sudo docker-compose up -d
