version: '2'
services:
  parser-server:
    build: ./
    image: parser-server
    container_name: parser-server
    ports:
      - "${APP_PORT}:1337"
    environment:
      APP_ID: '${APP_ID}'
      MASTER_KEY: '${MASTER_KEY}'
      DATABASE_URI: '${DATABASE_URI}'
      PARSE_MOUNT: '${PARSE_MOUNT}'
    restart: always
