version: '2'
services:
  parser-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ID: '${APP_ID}'
        MASTER_KEY: '${MASTER_KEY}'
        DATABASE_URI: '${DATABASE_URI}'
    image: parser-server
    container_name: parser-server
    volumes:
      - parser-server-sync:/var/www/parser-server:nocopy
    ports:
      - "${APP_PORT}:1337"
    environment:
      APP_ID: '${APP_ID}'
      MASTER_KEY: '${MASTER_KEY}'
      DATABASE_URI: '${DATABASE_URI}'
      PARSE_MOUNT: '${PARSE_MOUNT}'
    restart: always
volumes:
  parser-server-sync:
    external: true
