apiVersion: v1
kind: Pod
metadata:
  name: parser-server
  labels:
    app: parser-server
spec:
  containers:
    - name: parser-server
      image: gcr.io/qwiklabs-gcp-9190be42502290e5/parser-server:v1
      ports:
        - containerPort: 1337
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
